// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:kurie/data/models/bill.dart';
import 'package:kurie/data/models/notification_item.dart';
import 'package:kurie/data/models/reading.dart';
import 'package:kurie/data/models/submeter.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BillAdapter());
    registerAdapter(NotificationItemAdapter());
    registerAdapter(ReadingAdapter());
    registerAdapter(SubmeterAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BillAdapter());
    registerAdapter(NotificationItemAdapter());
    registerAdapter(ReadingAdapter());
    registerAdapter(SubmeterAdapter());
  }
}
